In [1]:
import pandas as pd
import sys
sys.path.insert(0, 'D:/10 A KAI 2/week 3/Insurance_Claim_Analysis/')

In [2]:
from scripts.GenderHypotesis import ABHypothesisTest
from scripts.Basic_stat import InsuranceBasicStast

In [3]:
df = pd.read_csv('../data/MachineLearningRating_v3.txt', sep='|')

C:\Users\marta\AppData\Local\Temp\ipykernel_6300\1274272554.py:1: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/MachineLearningRating_v3.txt', sep='|')

In [12]:
df

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000093,31520,389,2015-04-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000094,31520,389,2015-06-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000095,31520,389,2015-08-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000096,31519,389,2014-07-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0
1000097,31519,389,2015-02-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0

In [4]:
result = InsuranceBasicStast(df)

In [5]:
result.rename_variable_value_name()

In [6]:
# Gender vs TotalClaims (Numerical Metric) (TotalClaims as the metric)
gender_test = ABHypothesisTest(df, feature_col='Gender', metric_col='TotalClaims', group_a_values=['Male'], group_b_values=['Female'])
gender_test.run_test()

Number of data points in Group A: 42817
Number of data points in Group B: 6755
Fail to reject the null hypothesis. No significant difference between the groups for TotalClaims.
T-statistic: -0.24803623812388725, p-value: 0.8041073961270343
Mean TotalClaims for Group A: 32.620312390266385
Mean TotalClaims for Group B: 37.04605451452467

##### Gender Conclusion:
#### Based on the statistical evidence, we conclude that there is no significant risk difference between men and women when it comes to TotalClaims.
#### In practical terms, gender does not seem to play a significant role in influencing the number of TotalClaims. Therefore, both genders can be considered statistically equivalent in terms of risk, based on the TotalClaims metric.

In [7]:
group_a_values = ['Gauteng', 'Western Cape', 'Mpumalanga', 'Free State',]  # Group A: Gauteng and Western Cape
group_b_values = ['KwaZulu-Natal', 'Eastern Cape','Limpopo', 'North West','Northern Cape']  # Group B: KwaZulu-Natal and Eastern Cape

# Run the test on 'TotalClaims'
province_test = ABHypothesisTest(df, feature_col='Province', metric_col='TotalClaims', group_a_values=group_a_values, group_b_values=group_b_values)
province_test.run_test()

Number of data points in Group A: 625478
Number of data points in Group B: 374620
Fail to reject the null hypothesis. No significant difference between the groups for TotalClaims.
T-statistic: 1.3988688564136376, p-value: 0.161852623379416
Mean TotalClaims for Group A: 67.44205206763134
Mean TotalClaims for Group B: 60.55209633106577

In [16]:
df['PostalCode'].nunique()

888

In [17]:
from scripts.Hypotesis_multivalued import ABHypothesisTest

In [19]:
# Create an instance of ABHypothesisTest
province_test = ABHypothesisTest(df, feature_col='Province', metric_col='TotalClaims',
                                  group_a_values=[], group_b_values=[])

# Define groups based on a criteria value (for example, average total claims)
criteria_value = df['TotalClaims'].mean()  # You can set any value based on your analysis
province_test.define_groups_based_on_criteria(criteria_value)

# Run the test
province_test.run_test()

Group A: ['Gauteng', 'KwaZulu-Natal']
Group B: ['Eastern Cape', 'Free State', 'Limpopo', 'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape']
Number of data points in Group A: 563646
Number of data points in Group B: 436452
Reject the null hypothesis. Significant difference between the groups for TotalClaims.
T-statistic: 6.03587185694927, p-value: 1.58161999176637e-09
Mean TotalClaims for Group A: 77.52300366921855
Mean TotalClaims for Group B: 48.50937845298316

##### conclusion 
##### If a significant difference is detected, it implies that the provinces with higher average total claims (Group A) differ from those with lower average claims (Group B) in a statistically meaningful way. This could be indicative of underlying factors affecting claim amounts in these regions.

In [20]:
# Create an instance of ABHypothesisTest
province_test = ABHypothesisTest(df, feature_col='PostalCode', metric_col='TotalClaims',
                                  group_a_values=[], group_b_values=[])

# Define groups based on a criteria value (for example, average total claims)
criteria_value = df['TotalClaims'].mean()  # You can set any value based on your analysis
province_test.define_groups_based_on_criteria(criteria_value)

# Run the test
province_test.run_test()

Group A: [5, 21, 31, 44, 49, 64, 81, 122, 125, 139, 153, 157, 175, 177, 179, 181, 182, 183, 184, 186, 198, 200, 201, 277, 302, 303, 307, 309, 311, 335, 404, 449, 456, 466, 467, 477, 631, 700, 708, 737, 920, 945, 1020, 1024, 1030, 1039, 1060, 1126, 1342, 1401, 1425, 1426, 1431, 1454, 1501, 1507, 1540, 1548, 1610, 1618, 1665, 1682, 1700, 1739, 1751, 1754, 1759, 1774, 1791, 1805, 1834, 1852, 1863, 1865, 1868, 1874, 1947, 1949, 2000, 2010, 2031, 2037, 2056, 2062, 2063, 2066, 2070, 2091, 2093, 2094, 2143, 2157, 2191, 2194, 2196, 2198, 2351, 2745, 2920, 3000, 3170, 3350, 3609, 3610, 3624, 3630, 3635, 3651, 3700, 3815, 3855, 4000, 4001, 4004, 4008, 4023, 4027, 4030, 4031, 4037, 4051, 4052, 4056, 4057, 4058, 4060, 4063, 4065, 4066, 4068, 4069, 4087, 4091, 4092, 4093, 4094, 4099, 4105, 4132, 4137, 4145, 4171, 4200, 4310, 4339, 4359, 4360, 4380, 4401, 4680, 4820, 5050, 5090, 5322, 5660, 5700, 6000, 6212, 6213, 6835, 6836, 7133, 7140, 7144, 7160, 7441, 7450, 7455, 7581, 7700, 7751, 7764, 7783, 7785, 7793, 7802, 7947, 7975, 8000, 8060, 9323, 9756, 9781]
Group B: [1, 2, 4, 6, 7, 8, 17, 22, 29, 35, 37, 46, 54, 66, 84, 101, 112, 116, 118, 120, 121, 129, 132, 143, 147, 149, 151, 152, 154, 161, 162, 164, 168, 172, 187, 190, 192, 193, 194, 195, 196, 199, 208, 220, 250, 258, 264, 268, 269, 284, 286, 292, 299, 300, 301, 305, 308, 310, 314, 316, 317, 318, 320, 322, 325, 331, 333, 337, 338, 340, 351, 355, 356, 360, 362, 365, 370, 371, 379, 380, 382, 388, 399, 400, 402, 407, 414, 422, 430, 431, 450, 453, 455, 457, 458, 459, 462, 465, 469, 470, 472, 473, 474, 475, 476, 479, 485, 486, 495, 510, 530, 555, 556, 557, 561, 600, 607, 608, 609, 617, 621, 623, 628, 690, 699, 721, 727, 736, 738, 739, 742, 743, 745, 746, 748, 751, 790, 802, 807, 812, 821, 827, 837, 902, 925, 931, 939, 942, 950, 951, 970, 982, 984, 993, 1000, 1003, 1021, 1022, 1023, 1026, 1027, 1034, 1035, 1038, 1047, 1050, 1052, 1053, 1054, 1055, 1057, 1058, 1059, 1061, 1062, 1064, 1068, 1072, 1085, 1098, 1120, 1123, 1124, 1127, 1129, 1133, 1150, 1154, 1185, 1240, 1245, 1250, 1280, 1360, 1365, 1372, 1389, 1405, 1421, 1423, 1424, 1441, 1448, 1449, 1455, 1457, 1458, 1459, 1460, 1462, 1466, 1471, 1474, 1475, 1491, 1494, 1496, 1513, 1519, 1520, 1522, 1541, 1550, 1559, 1560, 1570, 1571, 1575, 1577, 1612, 1619, 1620, 1625, 1629, 1630, 1631, 1632, 1640, 1666, 1685, 1687, 1688, 1692, 1693, 1709, 1710, 1724, 1725, 1740, 1742, 1743, 1744, 1745, 1747, 1748, 1757, 1779, 1781, 1794, 1801, 1803, 1804, 1806, 1807, 1809, 1811, 1812, 1813, 1818, 1819, 1820, 1821, 1824, 1827, 1828, 1829, 1830, 1833, 1835, 1837, 1841, 1851, 1860, 1861, 1862, 1864, 1867, 1869, 1875, 1884, 1900, 1914, 1928, 1930, 1932, 1939, 1940, 1948, 1963, 1980, 1982, 1983, 1984, 2001, 2007, 2008, 2014, 2017, 2018, 2019, 2021, 2028, 2040, 2055, 2057, 2061, 2069, 2090, 2092, 2095, 2125, 2128, 2146, 2170, 2188, 2189, 2190, 2192, 2193, 2195, 2197, 2210, 2230, 2231, 2375, 2380, 2410, 2415, 2420, 2470, 2499, 2500, 2502, 2507, 2530, 2531, 2534, 2570, 2571, 2574, 2610, 2619, 2620, 2735, 2740, 2744, 2754, 2766, 2791, 2835, 2840, 2841, 2860, 2865, 2868, 2869, 2870, 2876, 2880, 2881, 2882, 2890, 2930, 2940, 2951, 2952, 3010, 3080, 3105, 3107, 3135, 3150, 3180, 3200, 3201, 3203, 3217, 3242, 3245, 3250, 3257, 3270, 3276, 3290, 3297, 3300, 3306, 3310, 3370, 3380, 3381, 3600, 3602, 3607, 3612, 3613, 3615, 3616, 3629, 3650, 3652, 3655, 3660, 3670, 3680, 3740, 3742, 3750, 3780, 3802, 3830, 3837, 3838, 3865, 3880, 3882, 3887, 3900, 3910, 3915, 3920, 3925, 3934, 3935, 3950, 3965, 3968, 3969, 3973, 3974, 4005, 4011, 4016, 4019, 4025, 4053, 4059, 4061, 4062, 4067, 4070, 4071, 4074, 4075, 4084, 4089, 4100, 4110, 4111, 4125, 4126, 4133, 4140, 4144, 4148, 4150, 4170, 4180, 4182, 4184, 4220, 4240, 4250, 4260, 4270, 4275, 4302, 4309, 4319, 4340, 4342, 4399, 4400, 4405, 4430, 4449, 4450, 4454, 4455, 4457, 4470, 4480, 4490, 4491, 4691, 4700, 4730, 4800, 4810, 4811, 4930, 4960, 4980, 4990, 5000, 5040, 5070, 5099, 5100, 5120, 5130, 5140, 5143, 5160, 5170, 5180, 5185, 5200, 5201, 5209, 5219, 5247, 5252, 5253, 5319, 5320, 5321, 5326, 5362, 5365, 5380, 5410, 5435, 5455, 5470, 5480, 5500, 5600, 5601, 5608, 5611, 5614, 5670, 5687, 5720, 5900, 5920, 6001, 6025, 6059, 6070, 6105, 6120, 6139, 6140, 6200, 6201, 6205, 6211, 6229, 6231, 6241, 6242, 6280, 6350, 6390, 6500, 6506, 6570, 6571, 6600, 6625, 6655, 6705, 6708, 6720, 6810, 6838, 6840, 6848, 6850, 6875, 7000, 7100, 7101, 7103, 7130, 7195, 7200, 7220, 7280, 7310, 7340, 7350, 7380, 7395, 7405, 7406, 7437, 7439, 7442, 7456, 7460, 7463, 7490, 7493, 7500, 7501, 7503, 7525, 7530, 7532, 7540, 7550, 7560, 7569, 7570, 7571, 7579, 7580, 7582, 7583, 7600, 7612, 7620, 7626, 7646, 7655, 7690, 7745, 7750, 7755, 7760, 7763, 7766, 7780, 7782, 7784, 7786, 7788, 7789, 7790, 7798, 7800, 7801, 7806, 7888, 7925, 7941, 7945, 8001, 8005, 8017, 8020, 8040, 8051, 8149, 8160, 8165, 8170, 8190, 8240, 8271, 8301, 8306, 8309, 8345, 8446, 8447, 8460, 8530, 8566, 8570, 8575, 8577, 8580, 8584, 8586, 8599, 8601, 8701, 9300, 9301, 9306, 9325, 9334, 9431, 9445, 9447, 9459, 9499, 9600, 9700, 9720, 9725, 9730, 9744, 9745, 9750, 9752, 9762, 9830, 9868, 9869, 9870]
Number of data points in Group A: 453712
Number of data points in Group B: 546386
Reject the null hypothesis. Significant difference between the groups for TotalClaims.
T-statistic: 16.906668593770227, p-value: 4.101360817108941e-64
Mean TotalClaims for Group A: 109.08482410706164
Mean TotalClaims for Group B: 28.13844508358303

#### Interpretation
#### Null Hypothesis: There is no significant difference between the means of TotalClaims in Group A and Group B. Alternative Hypothesis: There is a significant difference between the means of TotalClaims in Group A and Group B.

In [22]:
# Create an instance of ABHypothesisTest
province_test = ABHypothesisTest(df, feature_col='PostalCode', metric_col='TotalPremium',
                                  group_a_values=[], group_b_values=[])

# Define groups based on a criteria value (for example, average total claims)
criteria_value = df['TotalPremium'].mean()  # You can set any value based on your analysis
province_test.define_groups_based_on_criteria(criteria_value)

# Run the test
province_test.run_test()

Group A: [4, 8, 17, 21, 29, 31, 35, 37, 44, 54, 64, 81, 101, 112, 116, 118, 120, 121, 125, 132, 139, 149, 152, 157, 161, 168, 175, 179, 181, 182, 184, 187, 193, 194, 195, 198, 199, 200, 201, 250, 258, 264, 268, 269, 277, 292, 301, 308, 309, 317, 335, 337, 338, 340, 351, 355, 356, 362, 371, 400, 402, 414, 449, 453, 455, 456, 457, 459, 462, 465, 466, 473, 486, 510, 556, 557, 561, 600, 607, 608, 617, 623, 628, 631, 700, 721, 727, 738, 739, 743, 746, 748, 807, 812, 821, 827, 902, 920, 925, 931, 939, 942, 945, 950, 951, 982, 984, 1023, 1024, 1026, 1027, 1034, 1047, 1050, 1052, 1054, 1055, 1058, 1061, 1068, 1098, 1120, 1126, 1127, 1133, 1150, 1185, 1240, 1245, 1280, 1360, 1365, 1389, 1423, 1424, 1425, 1426, 1431, 1449, 1457, 1459, 1462, 1466, 1474, 1494, 1496, 1501, 1507, 1513, 1540, 1541, 1560, 1577, 1612, 1625, 1629, 1631, 1632, 1665, 1682, 1687, 1688, 1693, 1700, 1709, 1725, 1739, 1740, 1742, 1743, 1747, 1751, 1754, 1757, 1759, 1779, 1791, 1794, 1803, 1804, 1805, 1806, 1818, 1819, 1820, 1821, 1828, 1829, 1833, 1834, 1835, 1837, 1841, 1861, 1862, 1864, 1869, 1874, 1884, 1900, 1928, 1932, 1939, 1940, 1947, 1948, 1949, 1983, 1984, 2008, 2010, 2014, 2019, 2021, 2028, 2031, 2040, 2055, 2057, 2061, 2062, 2066, 2070, 2090, 2093, 2095, 2125, 2146, 2188, 2192, 2196, 2197, 2230, 2351, 2380, 2415, 2500, 2574, 2610, 2619, 2835, 2860, 2868, 2881, 2920, 2930, 2951, 3000, 3010, 3105, 3107, 3135, 3170, 3200, 3203, 3217, 3245, 3257, 3276, 3290, 3297, 3310, 3350, 3370, 3380, 3600, 3602, 3607, 3609, 3610, 3624, 3629, 3630, 3635, 3650, 3651, 3660, 3670, 3680, 3700, 3740, 3742, 3750, 3780, 3802, 3815, 3830, 3855, 3880, 3887, 3900, 3920, 3925, 3934, 3935, 3950, 3965, 3968, 3969, 4000, 4001, 4004, 4016, 4023, 4027, 4030, 4031, 4037, 4051, 4052, 4053, 4056, 4057, 4058, 4059, 4060, 4061, 4062, 4063, 4065, 4066, 4070, 4071, 4074, 4075, 4084, 4089, 4091, 4094, 4100, 4126, 4132, 4133, 4137, 4140, 4144, 4150, 4170, 4171, 4180, 4182, 4200, 4220, 4240, 4250, 4270, 4275, 4309, 4310, 4319, 4339, 4342, 4359, 4360, 4380, 4399, 4401, 4430, 4449, 4450, 4455, 4457, 4470, 4480, 4490, 4491, 4680, 4691, 4730, 4800, 4811, 4820, 4930, 4980, 4990, 5040, 5090, 5120, 5130, 5140, 5170, 5180, 5201, 5209, 5219, 5247, 5252, 5253, 5319, 5320, 5321, 5322, 5365, 5380, 5410, 5435, 5480, 5500, 5600, 5601, 5611, 5614, 5660, 5670, 5700, 5720, 5900, 5920, 6070, 6120, 6139, 6140, 6201, 6205, 6211, 6212, 6213, 6231, 6241, 6242, 6280, 6390, 6500, 6506, 6835, 6836, 6850, 6875, 7100, 7101, 7130, 7133, 7144, 7195, 7200, 7220, 7380, 7395, 7437, 7441, 7442, 7455, 7460, 7490, 7493, 7500, 7525, 7550, 7570, 7579, 7600, 7612, 7620, 7655, 7690, 7751, 7755, 7782, 7786, 7798, 7802, 7806, 7975, 8000, 8020, 8040, 8060, 8165, 8170, 8271, 8306, 8345, 8446, 8447, 8530, 8566, 8577, 8580, 8599, 8601, 8701, 9301, 9323, 9325, 9334, 9431, 9445, 9459, 9499, 9600, 9700, 9725, 9730, 9744, 9745, 9750, 9752, 9756, 9830, 9868, 9870]
Group B: [1, 2, 5, 6, 7, 22, 46, 49, 66, 84, 122, 129, 143, 147, 151, 153, 154, 162, 164, 172, 177, 183, 186, 190, 192, 196, 208, 220, 284, 286, 299, 300, 302, 303, 305, 307, 310, 311, 314, 316, 318, 320, 322, 325, 331, 333, 360, 365, 370, 379, 380, 382, 388, 399, 404, 407, 422, 430, 431, 450, 458, 467, 469, 470, 472, 474, 475, 476, 477, 479, 485, 495, 530, 555, 609, 621, 690, 699, 708, 736, 737, 742, 745, 751, 790, 802, 837, 970, 993, 1000, 1003, 1020, 1021, 1022, 1030, 1035, 1038, 1039, 1053, 1057, 1059, 1060, 1062, 1064, 1072, 1085, 1123, 1124, 1129, 1154, 1250, 1342, 1372, 1401, 1405, 1421, 1441, 1448, 1454, 1455, 1458, 1460, 1471, 1475, 1491, 1519, 1520, 1522, 1548, 1550, 1559, 1570, 1571, 1575, 1610, 1618, 1619, 1620, 1630, 1640, 1666, 1685, 1692, 1710, 1724, 1744, 1745, 1748, 1774, 1781, 1801, 1807, 1809, 1811, 1812, 1813, 1824, 1827, 1830, 1851, 1852, 1860, 1863, 1865, 1867, 1868, 1875, 1914, 1930, 1963, 1980, 1982, 2000, 2001, 2007, 2017, 2018, 2037, 2056, 2063, 2069, 2091, 2092, 2094, 2128, 2143, 2157, 2170, 2189, 2190, 2191, 2193, 2194, 2195, 2198, 2210, 2231, 2375, 2410, 2420, 2470, 2499, 2502, 2507, 2530, 2531, 2534, 2570, 2571, 2620, 2735, 2740, 2744, 2745, 2754, 2766, 2791, 2840, 2841, 2865, 2869, 2870, 2876, 2880, 2882, 2890, 2940, 2952, 3080, 3150, 3180, 3201, 3242, 3250, 3270, 3300, 3306, 3381, 3612, 3613, 3615, 3616, 3652, 3655, 3837, 3838, 3865, 3882, 3910, 3915, 3973, 3974, 4005, 4008, 4011, 4019, 4025, 4067, 4068, 4069, 4087, 4092, 4093, 4099, 4105, 4110, 4111, 4125, 4145, 4148, 4184, 4260, 4302, 4340, 4400, 4405, 4454, 4700, 4810, 4960, 5000, 5050, 5070, 5099, 5100, 5143, 5160, 5185, 5200, 5326, 5362, 5455, 5470, 5608, 5687, 6000, 6001, 6025, 6059, 6105, 6200, 6229, 6350, 6570, 6571, 6600, 6625, 6655, 6705, 6708, 6720, 6810, 6838, 6840, 6848, 7000, 7103, 7140, 7160, 7280, 7310, 7340, 7350, 7405, 7406, 7439, 7450, 7456, 7463, 7501, 7503, 7530, 7532, 7540, 7560, 7569, 7571, 7580, 7581, 7582, 7583, 7626, 7646, 7700, 7745, 7750, 7760, 7763, 7764, 7766, 7780, 7783, 7784, 7785, 7788, 7789, 7790, 7793, 7800, 7801, 7888, 7925, 7941, 7945, 7947, 8001, 8005, 8017, 8051, 8149, 8160, 8190, 8240, 8301, 8309, 8460, 8570, 8575, 8584, 8586, 9300, 9306, 9447, 9720, 9762, 9781, 9869]
Number of data points in Group A: 335492
Number of data points in Group B: 664606
Reject the null hypothesis. Significant difference between the groups for TotalPremium.
T-statistic: 70.56666563102054, p-value: 0.0
Mean TotalPremium for Group A: 84.71972404835454
Mean TotalPremium for Group B: 50.388911680005435

### Overall, these results suggest that Group A and Group B differ significantly with respect to TotalPremium, and this difference is statistically significant and substantial.